apiVersion: v1
kind: Service
metadata:
  name: db
  namespace: blog-site
spec:
  selector:
    app: mysql
  ports:
    - port: 3306
      targetPort: 3306
  clusterIP: None   # headless service, stable DNS name "db" for the backend to use
